version: '3'

services:
  mysql:
    container_name: mysql01
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'admin'
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql:/var/lib/mysql'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
